### ISSUE TITLE
rules_ruby not using specified SDK version

### ISSUE THREAD

**Issue by jgao54** [bazelruby/rules_ruby#148]
We are testing out the flow for installing ruby 2.7.6 with `ruby-build`. (Note this first requires bumping the `ruby-build` version, which I created a [PR](https://github.com/bazelruby/rules_ruby/pull/147) here.

With the version specified in WORKSPACE:
```
load("@bazelruby_rules_ruby//ruby:deps.bzl", "rules_ruby_select_sdk")
rules_ruby_select_sdk(version = "2.7.6")
```

I can confirm that ruby interpreter that's installed to the `@org_ruby_lang_ruby_toolchain` external repository is the right version:
```
➜  org_ruby_lang_ruby_toolchain build/bin/ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
```

However, running any `ruby_library` target defaults to use the ruby version that's found first in PATH. On my macos machine, when running `bazel run //<my_binary_target>`, I get this error:

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require': incompatible library version...`

I think this requires updating the way [the binary wrapper](https://github.com/bazelruby/rules_ruby/blob/master/ruby/private/binary_wrapper.tpl) is implemented:

```
#!/usr/bin/env ruby

...

def find_ruby_binary
  File.join(
    RbConfig::CONFIG['bindir'],
    RbConfig::CONFIG['ruby_install_name'],
  )
end
```
This will end up using the first ruby found in PATH rather than the version that's specified in the SDK.

**Comment by jgao54** [comment]
I missed [this issue](https://github.com/bazelruby/rules_ruby/issues/115), which points to the same bug.

**Comment by kigster** [comment]
That's not the issue afaik.

Thank you for including your error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require': incompatible library version...
```

What this error tells you is that the Ruby being used here is the system Ruby that comes with Os-X. It's a Ruby 2.6, and it's installed into a read only file system. So naturally you can't install any gems there.

The rules expect your ruby to be installed by rbenv.

In order for rbenv to work, you must add the following to your shell initialization file:

```
eval "$(rbenv init -)"
```
